--create a new database and schema 
USE DATABASE LA_DB;
USE SCHEMA LA_DB.LA_SCHEMA;

---Create a sample table
CREATE OR REPLACE TABLE LA_DB.LA_SCHEMA.EMPLOYEES
(
  ID INT,
  NAME STRING,
  DEPARTMENT STRING
);

--Insert the data to employee table
INSERT INTO LA_DB.LA_SCHEMA.EMPLOYEES (ID,NAME,DEPARTMENT) VALUES
(1,'ALICE','ENGINEERING'),
(2,'BOB','FINANCE');

--DISPLAY THE DATA
SELECT * FROM LA_DB.LA_SCHEMA.EMPLOYEES;
